# Generated by Django 3.1.2 on 2020-10-18 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20201018_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
