# Generated by Django 3.1.2 on 2020-10-30 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0007_auto_20201022_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['title'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies_images'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.SlugField(max_length=32, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='specialties_images'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
    ]
