# Generated by Django 3.1.2 on 2020-11-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20201031_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='expirience',
            new_name='experience',
        ),
    ]
