# Generated by Django 3.1.2 on 2020-11-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_auto_20201101_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='specialty',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
