# Generated by Django 3.1.2 on 2020-11-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_auto_20201101_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.CharField(max_length=50),
        ),
    ]
